apiVersion: v1
kind: Service
metadata:
  name: web-app-service
spec:
  type: NodePort
  ports:
    - targetPort: 80
      nodePort: 30008
      port: 80
  selector:
      app: web-app-pod
      type: front-end-pod
