apiVersion: v1
kind: Service
metadata:
  name: web-app-service
spec:
  type: NodePort
  ports:
    - targetPort: 5000
      nodePort: 30008
      port: 5000
  selector:
      app: web-app-pod
      type: front-end-pod
